### ISSUE TITLE
GUI is not responding after selecting data

### ISSUE THREAD

**Issue by its-shin-donghoon** [jwouters91/shybrid#8] opened 2020-05-14 02:21 UTC
Hi team Shybrid,

Thank you for sharing such a useful tool.

I am trying to generate a hybrid ground truth dataset with shybrid but the GUI is not responding after selecting data. It works well with example data but it doesn't with my data. I believe the four input files are as it should be, so I don't know how to figure out. 

1. The extracellular recording is .dat file and was sampled with 30kHz and highpass filtered with 150Hz.
2. The initial spike sorting file is in phy-format and the folder stores kilosort & phy output files and unchanged.
3. Probe file is used by the lab for a long time and I modified like Shybrid example. (attached.)
4. parameter file is same as Shybrid example. (attached)

Please help! Thank you.

![list_of_files_in_the_folder](https://user-images.githubusercontent.com/57731466/81885304-1504e080-9568-11ea-8341-3a689673d97b.PNG)
![prbfile](https://user-images.githubusercontent.com/57731466/81885305-159d7700-9568-11ea-8704-4dd2ae937dfc.PNG)
![SHYBRID_not_responding](https://user-images.githubusercontent.com/57731466/81885306-159d7700-9568-11ea-904a-815925391c81.PNG)
![yamlfile](https://user-images.githubusercontent.com/57731466/81885307-159d7700-9568-11ea-93c7-b1bf91d029b9.PNG)

**Comment by jwouters91** [comment] 2020-05-14 06:53
Hi there,

Thanks for sharing this issue. I think your file structure looks fine from what I can tell. Could you check and report back on the following questions:

1. After you have loaded the data, can you click again on the "select data" button and will it show the browsing pop-up again? Or is the GUI completely frozen?

2. Does your cluster_group.tsv file contain any "good" labels? That is, have you identified (and saved) any single-unit clusters during manual curation in the phy GUI?

Best,

Jasper

**Comment by jwouters91** [comment] 2020-05-14 07:08
Furthermore, please consider this open issue: https://github.com/jwouters91/shybrid/issues/2

But since you were able to run the hybridization process with the example data, this issue doesn't seem to impact you.

**Comment by its-shin-donghoon** [comment] 2020-05-14 15:15
Hi Jasper,

Thank you for the quick response!

1. The GUI is completely frozen.
2. It has good labels. Yes, I have done manual curation in the phy GUI and have good labeled units.
3. I have tried with double backslash and it's remained the same.

Best,
Donghoon

**Comment by jwouters91** [comment] 2020-05-14 18:52
Hi Donghoon,

Ok, that's good already!

Since you are able to run it with the example data, I am afraid that it might be related to your data specifically. Are you in a position to share with me this data or another non-working example, such that I can try to recreate the freezing behaviour?

In case you are willing to temporarily share the data, can you also provide me with additional information about your python environment by pasting the result from "conda list -n <virtualenv_name>"?

Best,

Jasper

PS: if the sharing requires my e-mail you can use the following one: jasperwouters@gmail.com

**Comment by its-shin-donghoon** [comment] 2020-05-14 20:22
Hi Jasper,

Thank you again for the quick response! I sent you e-mail with the data.
Please let me know how it goes!

Best,
Donghoon

**Comment by jwouters91** [comment] 2020-05-15 07:35
Hi Donghoon!

Thanks for sharing your data. Good news: I've been able to reproduce the freezing behaviour and I have also identified the problem. The problem is 100 percent on our side and is related to the use of a single column probe. The data you shared was fully correct! I will provide a patch for this issue ASAP.

Best,

Jasper

**Comment by jwouters91** [comment] 2020-05-15 15:45
Hi Donghoon,

I committed a patch that I briefly tested on your data. Can you verify that it is also functioning for you? You can install this patch as follows:

`pip install --force-reinstall git+https://github.com/jwouters91/shybrid.git`

If you approve this patch I will upload it to PyPI as well.

Thanks for reporting this bug, and don't hesitate to post any other issue you encounter!

Best,

Jasper

**Comment by its-shin-donghoon** [comment] 2020-05-15 16:46
Hi Jasper,

It works very well. I'll try to use full function of SHYBRID generating hybrid ground truth. If I encounter any other issues, I'll ask you.

Thank you again for sharing the tool and solving the issue.

Best,
Donghoon

**Closed** 2020-05-15 19:16 UTC
Labels: bug, question
